//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakPisir.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakPisirDBEntities : DbContext
    {
        public BakPisirDBEntities()
            : base("name=BakPisirDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTBL> CategoryTBL { get; set; }
        public virtual DbSet<CommentTBL> CommentTBL { get; set; }
        public virtual DbSet<LogTBL> LogTBL { get; set; }
        public virtual DbSet<RecipeTBL> RecipeTBL { get; set; }
        public virtual DbSet<RequestTBL> RequestTBL { get; set; }
        public virtual DbSet<StepTBL> StepTBL { get; set; }
        public virtual DbSet<SubCategoryTBL> SubCategoryTBL { get; set; }
        public virtual DbSet<SubTransitionTBL> SubTransitionTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserTBL> UserTBL { get; set; }
    }
}
