//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakPisir.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentTBL
    {
        public int commentId { get; set; }
        public Nullable<int> recipeId { get; set; }
        public Nullable<int> userId { get; set; }
        public string comment { get; set; }
        public Nullable<int> parentId { get; set; }
        public string commentImageUrl { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
    
        public virtual RecipeTBL RecipeTBL { get; set; }
        public virtual UserTBL UserTBL { get; set; }
    }
}
