//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakPisir.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTBL
    {
        public int requestId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public string phone { get; set; }
        public string username { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<bool> agreement { get; set; }
        public string identityNumber { get; set; }
        public string password { get; set; }
    }
}
