//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakPisir.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategoryTBL()
        {
            this.SubTransitionTBL = new HashSet<SubTransitionTBL>();
        }
    
        public int subCategoryId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string subCategoryName { get; set; }
        public Nullable<int> recipeId { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual CategoryTBL CategoryTBL { get; set; }
        public virtual RecipeTBL RecipeTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTransitionTBL> SubTransitionTBL { get; set; }
    }
}
