//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakPisir.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTBL()
        {
            this.CommentTBL = new HashSet<CommentTBL>();
            this.LogTBL = new HashSet<LogTBL>();
            this.RecipeTBL = new HashSet<RecipeTBL>();
        }
    
        public int userId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public string phone { get; set; }
        public string username { get; set; }
        public Nullable<bool> userType { get; set; }
        public string password { get; set; }
        public string profilePictureUrl { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string identityNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentTBL> CommentTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTBL> LogTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeTBL> RecipeTBL { get; set; }
    }
}
